databases:
  - name: sortable
    databaseName: sortable
    user: sortable

services:
  - type: web
    name: sortable
    runtime: ruby
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sortable
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
